### ISSUE TITLE
Tab Panel Colours Not Obeying Themify

### ISSUE THREAD

**Issue by BobaDog** [jneilliii/OctoPrint-ConsolidatedTabs#24]
Hi,

Firstly, I really like your plugin.

However, I am having trouble getting the panels to obey the Themify settings. Please see images attached. 

I think I have added the correct CSS selectors but maybe not.

Can you help me please?

Thanks

<img width="732" alt="Octoprint Consolidated Tabs Error 2" src="https://user-images.githubusercontent.com/71286308/93123445-023e1c00-f6c0-11ea-9b70-8fc0f6bd88f6.PNG">
<img width="1920" alt="Octoprint Consolidated Tabs Error 1" src="https://user-images.githubusercontent.com/71286308/93123447-02d6b280-f6c0-11ea-8f65-9261e954f2b0.PNG">

**Comment by jneilliii** [comment]
check the box enable customizations.

**Comment by BobaDog** [comment]
Thanks for the prompt reply. My apologies. It was not checked in the image but it doesn’t make a difference when checked. Panels are still white. Thanks. 
    	
    	

    	Get Outlook for iOS
    
  




On Mon, Sep 14, 2020 at 8:19 PM +0100, "jneilliii" <notifications@github.com> wrote:















check the box enable customization.

**Comment by jneilliii** [comment]
Here are my settings and they work for me.
```
    themeify:
        customRules:
        -   enabled: false
            rule: background-color
            selector: .navbar-inner
            value: '#2f3136'
        -   enabled: false
            rule: background-color
            selector: .accordion
            value: '#2f3136'
        -   enabled: true
            rule: width
            selector: div.row-fluid.inline_thumbnail > img
            value: 100px
        -   enabled: true
            rule: display
            selector: div.row-fluid.inline_thumbnail > img
            value: block
        -   enabled: true
            rule: margin-left
            selector: div.row-fluid.inline_thumbnail > img
            value: auto
        -   enabled: true
            rule: margin-right
            selector: div.row-fluid.inline_thumbnail > img
            value: auto
        -   enabled: true
            rule: height
            selector: '#files > div > div.gcode_files > div.scroll-wrapper'
            value: 800px
        -   enabled: true
            rule: background-color
            selector: div.panel-heading
            value: '#2f3136'
        -   enabled: true
            rule: border-bottom
            selector: div.panel-heading
            value: '1px solid #fc8003'
        -   enabled: true
            rule: border
            selector: div.panel
            value: '1px solid #fc8003'
        -   enabled: true
            rule: background-color
            selector: div.panel
            value: '#2f3136'
        -   enabled: true
            rule: background-color
            selector: '#tabs_content'
            value: '#36393f'
        -   enabled: true
            rule: -webkit-box-shadow
            selector: '#tabs_content'
            value: unset
        -   enabled: true
            rule: box-shadow
            selector: '#tabs_content'
            value: unset
        -   enabled: true
            rule: border
            selector: '#sidebar'
            value: '1px solid #fc8003'
        -   enabled: true
            rule: border-top
            selector: .accordion-inner, .accordion-heading:gt(1)
            value: '1px solid #fc8003'
        -   enabled: true
            rule: border-radius
            selector: .accordion
            value: 4px
        -   enabled: true
            rule: background-color
            selector: .table thead tr.info > th, .table tbody tr td.info, .table tfoot
                tr.info > th
            value: '#36393f'
        -   enabled: true
            rule: color
            selector: div.x-axis-label
            value: '#dadadc'
        -   enabled: true
            rule: border-bottom
            selector: 'hr, #control h1'
            value: '1px solid #FC8003'
        -   enabled: true
            rule: border-top
            selector: hr
            value: '0'
        enableCustomization: true
```

![image](https://user-images.githubusercontent.com/5249455/93132695-170cb680-f6a4-11ea-94b2-275fb4e5b88a.png)
